[package]
name = "shrunner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Only used for the version memmapping the shellcode 
# mmap = "*"
